package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/abhinandkakkadi/snippetbox/internal/assert"
)


func TestPing(t *testing.T) {

	// Initiate a new httptest.ResponseRecorder
	rr := httptest.NewRecorder()

	// Initialize a new dummy http.Request
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// Call the handler by passing in http.ResponseRecorder to which status code,
	// response body and headers are written, rather than writing it directly to the connection
	ping(rr,r)

	// Result returns http.Response generated by the handler
	rs := rr.Result()

	// Check status code
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	// Check Response body
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}

	bytes.TrimSpace(body)

	assert.Equal(t,string(body),"OK")

}